stages:
  - test
  - teardown

include:
  - https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/templates/hidden-jobs.yml
  - https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/templates/teardown.yml


"1.0 (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - docker-ci
  extends: .test_docker_1_0

"1.1 (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - docker-ci
  extends: .test_docker_1_0

"Nightly (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - docker-ci
  extends: .test_docker_nightly
