name = "Correlation"
uuid = "51a50332-c1db-5759-b0b5-6c83453eca4c"
authors = ["Eric Davies <iamed2@gmail.com>", "Sam Morrison <sam.morrison@invenia.ca>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "0.7, 1.0"

[extras]
Correlation = "51a50332-c1db-5759-b0b5-6c83453eca4c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Correlation"]
